import { LexoRank } from '@/lib/utils';
import { LabelInterface, labels } from './labels';
import { Priority, priorities } from './priorities';
import { Project, projects } from './projects';
import { Status, status, StatusCategory } from './status';
import { User, users } from './users';

export interface Issue {
   id: string;
   identifier: string;
   title: string;
   description: string;
   status: Status;
   assignee: User | null;
   priority: Priority;
   labels: LabelInterface[];
   createdAt: string;
   /** Cycle the issue belongs to. Empty string = no cycle (backlog stock). */
   cycleId: string;
   project?: Project;
   subissues?: string[];
   rank: string;
   dueDate?: string;
}

/* -------------------------------------------------------------------------- */
/*                             Seed-based generation                          */
/* -------------------------------------------------------------------------- */

const statusById = (id: string): Status => {
   const found = status.find((s) => s.id === id);
   if (!found) throw new Error(`Unknown status id: ${id}`);
   return found;
};

/**
 * Compact issue seed:
 * [identifier, title, statusId, priorityIdx, assigneeIdx | null, labelIdxs, projectIdx | null, cycleId, createdAt, dueDate?]
 *
 * - priorityIdx: index in `priorities` (0 no-priority, 1 urgent, 2 high, 3 medium, 4 low)
 * - assigneeIdx / labelIdxs / projectIdx: indexes in `users` / `labels` / `projects`
 * - cycleId: '' = not planned in any cycle
 */
type IssueSeed = [
   string,
   string,
   string,
   number,
   number | null,
   number[],
   number | null,
   string,
   string,
   string?,
];

const seeds: IssueSeed[] = [
   /* ------------------------- Cycle 21 (current) ------------------------- */
   // Product Feedback (2)
   [
      'ADI-701',
      'Combobox: keyboard selection skips disabled options inconsistently',
      'product-feedback',
      2,
      0,
      [0, 8],
      0,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-702',
      'Date picker: month navigation feels laggy on low-end devices',
      'product-feedback',
      3,
      6,
      [5],
      9,
      '21',
      '2026-07-22',
   ],
   // In Progress (4)
   [
      'ADI-703',
      'Rework Dialog focus trap to support nested portals',
      'in-progress',
      1,
      2,
      [1, 8],
      2,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-704',
      'Add virtualization to Data Table for 10k+ rows',
      'in-progress',
      2,
      4,
      [5],
      9,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-705',
      'Ship CLI flag to scaffold components with test files',
      'in-progress',
      3,
      8,
      [2, 9],
      5,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-706',
      'Migrate color tokens to OKLCH with fallbacks',
      'in-progress',
      2,
      12,
      [4],
      1,
      '21',
      '2026-07-24',
   ],
   // Technical Review (2)
   [
      'ADI-707',
      'Refactor Tooltip positioning engine to floating middleware',
      'technical-review',
      2,
      1,
      [4],
      7,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-708',
      'Toast queue: collapse duplicate notifications',
      'technical-review',
      3,
      10,
      [2],
      11,
      '21',
      '2026-07-22',
   ],
   // Paused (1)
   [
      'ADI-709',
      'Carousel: momentum scrolling on trackpads',
      'paused',
      4,
      14,
      [2],
      0,
      '21',
      '2026-07-21',
   ],
   // Blocked (1)
   [
      'ADI-710',
      'Command palette: async sources hang when provider throws',
      'blocked',
      1,
      3,
      [1],
      0,
      '21',
      '2026-07-25',
   ],
   // Triage (1)
   [
      'ADI-711',
      'Report: Select dropdown clipped inside scrollable Sheet',
      'triage',
      0,
      null,
      [1],
      null,
      '21',
      '2026-07-30',
   ],
   // Todo (13)
   [
      'ADI-712',
      'Add skeleton variants for Card and Table',
      'to-do',
      3,
      5,
      [0],
      6,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-713',
      'Expose CSS variables for Radix Accordion animations',
      'to-do',
      4,
      null,
      [0],
      0,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-714',
      'Breadcrumb: support collapsed middle items with popover',
      'to-do',
      3,
      7,
      [2],
      3,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-715',
      'Form: surface async validation state on submit button',
      'to-do',
      2,
      9,
      [10],
      10,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-716',
      'Avatar group: overflow counter with tooltip listing users',
      'to-do',
      4,
      11,
      [2],
      6,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-717',
      'Number input: locale-aware decimal separators',
      'to-do',
      3,
      13,
      [10],
      10,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-718',
      'Docs: interactive playground for Badge variants',
      'to-do',
      4,
      15,
      [3],
      1,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-719',
      'Resizable panels: persist layout per page in memory',
      'to-do',
      3,
      16,
      [2],
      4,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-720',
      'Tabs: add vertical orientation with proper roving focus',
      'to-do',
      2,
      17,
      [8],
      0,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-721',
      'Progress: indeterminate state with reduced-motion fallback',
      'to-do',
      4,
      18,
      [8],
      11,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-722',
      'Chart palette: colorblind-safe categorical scale',
      'to-do',
      2,
      19,
      [8, 6],
      4,
      '21',
      '2026-07-29',
   ],
   [
      'ADI-723',
      'Sidebar: double-click on rail to collapse to icons',
      'to-do',
      4,
      0,
      [2],
      5,
      '21',
      '2026-07-30',
   ],
   [
      'ADI-724',
      'Dropdown: sub-menu opens off-screen near viewport edge',
      'to-do',
      2,
      null,
      [1],
      8,
      '21',
      '2026-07-31',
   ],
   // Done (10)
   [
      'ADI-725',
      'Fix Switch thumb misalignment in RTL layouts',
      'done',
      2,
      2,
      [1],
      10,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-726',
      'Memoize Table row renderer to cut re-renders by 60%',
      'done',
      1,
      4,
      [5],
      9,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-727',
      'Add aria-live region to inline form errors',
      'done',
      2,
      6,
      [8, 10],
      10,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-728',
      'Popover: flip to top when bottom space is insufficient',
      'done',
      3,
      8,
      [1],
      7,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-729',
      'Theme switcher: persist preference and honor system change',
      'done',
      3,
      10,
      [2],
      1,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-730',
      'Slider: snap points with haptic-like visual ticks',
      'done',
      4,
      12,
      [2],
      10,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-731',
      'Docs search: index component prop tables',
      'done',
      3,
      14,
      [3],
      3,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-732',
      'Checkbox: indeterminate propagation for nested lists',
      'done',
      2,
      16,
      [2],
      10,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-733',
      'Reduce icon bundle size with per-icon entrypoints',
      'done',
      2,
      18,
      [5],
      5,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-734',
      'Calendar: highlight today with subtle ring in dark mode',
      'done',
      4,
      1,
      [6],
      9,
      '21',
      '2026-07-27',
   ],
   // Shipped (2)
   [
      'ADI-735',
      'Release Empty State component with illustration slots',
      'shipped',
      3,
      3,
      [2],
      6,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-736',
      'Publish v2.4 with tree-shakable exports',
      'shipped',
      1,
      5,
      [5, 2],
      5,
      '21',
      '2026-07-29',
   ],
   // Canceled (1)
   [
      'ADI-737',
      'Prototype parallax hero for docs landing',
      'canceled',
      4,
      7,
      [6],
      3,
      '21',
      '2026-07-30',
   ],

   /* ------------------------ Cycle 22 (upcoming) ------------------------- */
   [
      'ADI-738',
      'Timeline component: draft API and anatomy',
      'to-do',
      2,
      9,
      [2, 6],
      6,
      '22',
      '2026-07-26',
   ],
   [
      'ADI-739',
      'File upload: chunked uploads with resumable state',
      'to-do',
      2,
      11,
      [2],
      10,
      '22',
      '2026-07-27',
   ],
   [
      'ADI-740',
      'Kbd component: platform-aware modifier rendering',
      'to-do',
      4,
      13,
      [0],
      0,
      '22',
      '2026-07-28',
   ],
   [
      'ADI-741',
      'Stepper: validate steps lazily on next',
      'to-do',
      3,
      15,
      [10],
      10,
      '22',
      '2026-07-29',
   ],
   [
      'ADI-742',
      'Density mode: compact spacing scale across components',
      'to-do',
      3,
      17,
      [0, 6],
      1,
      '22',
      '2026-07-30',
   ],
   [
      'ADI-743',
      'Docs: migration guide from v1 tokens to v2 tokens',
      'to-do',
      3,
      19,
      [3],
      3,
      '22',
      '2026-07-31',
   ],
   [
      'ADI-744',
      'Audit Dialog scroll locking on iOS Safari',
      'paused',
      2,
      0,
      [1, 8],
      2,
      '22',
      '2026-07-25',
   ],
   [
      'ADI-745',
      'Benchmark charts rendering vs. canvas fallback',
      'paused',
      3,
      2,
      [5],
      4,
      '22',
      '2026-07-26',
   ],

   /* ----------------------- Cycle 20 (completed) ------------------------- */
   [
      'ADI-681',
      'Add copy-to-clipboard button to code blocks in docs',
      'done',
      3,
      4,
      [3],
      3,
      '20',
      '2026-07-06',
   ],
   ['ADI-682', 'Fix Tabs indicator jump on font load', 'done', 2, 6, [1], 0, '20', '2026-07-07'],
   [
      'ADI-683',
      'Ship Combobox multi-select with tag input',
      'shipped',
      2,
      8,
      [2],
      10,
      '20',
      '2026-07-09',
   ],
   [
      'ADI-684',
      'Contrast pass on muted foreground colors',
      'done',
      2,
      10,
      [8],
      1,
      '20',
      '2026-07-11',
   ],
   [
      'ADI-685',
      'Table sticky header shadow only when scrolled',
      'done',
      4,
      12,
      [0],
      9,
      '20',
      '2026-07-13',
   ],
   [
      'ADI-686',
      'Deprecate legacy Grid in favor of layout primitives',
      'canceled',
      3,
      14,
      [4],
      6,
      '20',
      '2026-07-15',
   ],
   [
      'ADI-687',
      'Snapshot tests for all Badge permutations',
      'done',
      4,
      16,
      [9],
      6,
      '20',
      '2026-07-17',
   ],

   /* ----------------------- Cycle 19 (completed) ------------------------- */
   [
      'ADI-661',
      'Rewrite Tooltip docs with do/don’t examples',
      'done',
      3,
      1,
      [3],
      7,
      '19',
      '2026-06-22',
   ],
   [
      'ADI-662',
      'Fix focus ring clipped by overflow-hidden cards',
      'done',
      2,
      3,
      [1, 8],
      6,
      '19',
      '2026-06-24',
   ],
   ['ADI-663', 'Ship Sonner-based toast presets', 'shipped', 3, 5, [2], 11, '19', '2026-06-26'],
   ['ADI-664', 'Lazy-load heavy demos on docs pages', 'done', 2, 7, [5], 3, '19', '2026-06-28'],
   [
      'ADI-665',
      'Select: type-ahead across grouped options',
      'done',
      3,
      9,
      [2],
      8,
      '19',
      '2026-06-30',
   ],
   [
      'ADI-666',
      'Duplicate of ADI-662 reported from support',
      'duplicate',
      0,
      null,
      [1],
      6,
      '19',
      '2026-07-01',
   ],
   ['ADI-667', 'Storybook a11y addon in CI', 'done', 2, 11, [9, 8], 6, '19', '2026-07-03'],

   /* ----------------------- Cycle 18 (completed) ------------------------- */
   [
      'ADI-641',
      'Fix Sheet drag-to-close threshold on touch',
      'done',
      2,
      13,
      [1],
      2,
      '18',
      '2026-06-08',
   ],
   ['ADI-642', 'Add Input OTP component', 'shipped', 2, 15, [2], 10, '18', '2026-06-10'],
   [
      'ADI-643',
      'Prevent layout shift when scrollbar appears with Dialog',
      'done',
      2,
      17,
      [1],
      2,
      '18',
      '2026-06-12',
   ],
   [
      'ADI-644',
      'Document controlled vs uncontrolled patterns',
      'done',
      3,
      19,
      [3],
      3,
      '18',
      '2026-06-14',
   ],
   [
      'ADI-645',
      'Spike: CSS anchor positioning for popovers',
      'canceled',
      4,
      0,
      [4],
      7,
      '18',
      '2026-06-16',
   ],
   [
      'ADI-646',
      'Refactor Avatar to support fallback delays',
      'done',
      4,
      2,
      [4],
      6,
      '18',
      '2026-06-18',
   ],

   /* ----------------------- Cycle 17 (completed) ------------------------- */
   [
      'ADI-621',
      'Dark mode: fix border contrast on nested cards',
      'done',
      3,
      4,
      [1, 6],
      1,
      '17',
      '2026-05-25',
   ],
   ['ADI-622', 'Ship Pagination compound component', 'shipped', 2, 6, [2], 9, '17', '2026-05-27'],
   [
      'ADI-623',
      'Add usage analytics to docs code copy events',
      'done',
      4,
      8,
      [3],
      3,
      '17',
      '2026-05-29',
   ],
   ['ADI-624', 'Textarea: autosize with max rows', 'done', 3, 10, [2], 10, '17', '2026-06-01'],
   [
      'ADI-625',
      'Fix Menubar closing when moving across triggers',
      'done',
      2,
      12,
      [1],
      8,
      '17',
      '2026-06-03',
   ],
   [
      'ADI-626',
      'Explore Houdini paint worklet for gradients',
      'canceled',
      4,
      14,
      [4],
      1,
      '17',
      '2026-06-05',
   ],

   /* ----------------------- Cycle 16 (completed) ------------------------- */
   [
      'ADI-601',
      'Set up visual regression tests with Playwright',
      'done',
      2,
      16,
      [9],
      6,
      '16',
      '2026-05-11',
   ],
   [
      'ADI-602',
      'Fix Tooltip flicker when trigger re-renders',
      'done',
      2,
      18,
      [1],
      7,
      '16',
      '2026-05-13',
   ],
   [
      'ADI-603',
      'Ship Scroll Area with custom scrollbar styling',
      'shipped',
      3,
      1,
      [2],
      0,
      '16',
      '2026-05-15',
   ],
   ['ADI-604', 'Normalize z-index scale across overlays', 'done', 2, 3, [4], 2, '16', '2026-05-17'],
   [
      'ADI-605',
      'Add French and Spanish docs translations',
      'done',
      4,
      5,
      [10],
      3,
      '16',
      '2026-05-19',
   ],

   /* --------------------------- Backlog stock ---------------------------- */
   [
      'ADI-801',
      'Explore container queries for responsive Card',
      'backlog',
      3,
      null,
      [0],
      6,
      '',
      '2026-06-02',
   ],
   [
      'ADI-802',
      'Tree view component with async children',
      'backlog',
      3,
      null,
      [2],
      6,
      '',
      '2026-06-05',
   ],
   [
      'ADI-803',
      'Color picker: eyedropper API integration',
      'backlog',
      4,
      null,
      [2],
      10,
      '',
      '2026-06-09',
   ],
   [
      'ADI-804',
      'Rich text editor primitives exploration',
      'backlog',
      3,
      null,
      [2, 4],
      null,
      '',
      '2026-06-12',
   ],
   [
      'ADI-805',
      'Drag handle affordance for sortable lists',
      'backlog',
      4,
      null,
      [0],
      9,
      '',
      '2026-06-15',
   ],
   ['ADI-806', 'Print stylesheet for docs pages', 'backlog', 4, null, [3], 3, '', '2026-06-18'],
   ['ADI-807', 'High-contrast theme preset', 'backlog', 3, null, [8, 6], 1, '', '2026-06-21'],
   [
      'ADI-808',
      'Skeleton auto-generation from component slots',
      'backlog',
      4,
      null,
      [4],
      6,
      '',
      '2026-06-24',
   ],
   ['ADI-809', 'Masonry layout primitive', 'backlog', 4, null, [2], 4, '', '2026-06-27'],
   [
      'ADI-810',
      'Investigate React Compiler compatibility',
      'backlog',
      2,
      null,
      [5, 9],
      5,
      '',
      '2026-06-30',
   ],
   [
      'ADI-811',
      'Currency input with min/max and formatting',
      'backlog',
      3,
      null,
      [10],
      10,
      '',
      '2026-07-03',
   ],
   [
      'ADI-812',
      'Docs: add keyboard shortcuts cheat sheet',
      'backlog',
      4,
      null,
      [3],
      3,
      '',
      '2026-07-06',
   ],
   [
      'ADI-813',
      'Idea: AI-assisted theme generator from a brand color',
      'idea',
      0,
      null,
      [6],
      1,
      '',
      '2026-07-08',
   ],
   [
      'ADI-814',
      'Idea: Figma plugin exporting tokens to CSS variables',
      'idea',
      0,
      null,
      [6, 2],
      1,
      '',
      '2026-07-10',
   ],
   [
      'ADI-815',
      'Idea: playground sharing via URL snapshots',
      'idea',
      0,
      null,
      [3],
      3,
      '',
      '2026-07-12',
   ],
   [
      'ADI-816',
      'Idea: motion presets pack (spring, snappy, gentle)',
      'idea',
      0,
      null,
      [2],
      0,
      '',
      '2026-07-14',
   ],
   ['ADI-817', 'Idea: CLI codemod for breaking changes', 'idea', 0, null, [5], 5, '', '2026-07-16'],
   ['ADI-818', 'Idea: docs dark-mode illustrations', 'idea', 0, null, [6], 3, '', '2026-07-18'],
   [
      'ADI-819',
      'Report: Combobox crashes with empty option groups',
      'triage',
      1,
      null,
      [1],
      8,
      '',
      '2026-07-29',
   ],
   [
      'ADI-820',
      'Report: Table header wraps awkwardly in Safari 17',
      'triage',
      0,
      null,
      [1],
      9,
      '',
      '2026-07-30',
   ],
   [
      'ADI-821',
      'Request: expose Tooltip open delay as prop',
      'triage',
      0,
      null,
      [0],
      7,
      '',
      '2026-07-31',
   ],

   /* ----------------------------------------------------------------- */
   /*         Batch 2 — extra issues (compact single-line seeds)         */
   /* ----------------------------------------------------------------- */
   /* Cycle 16 (completed — May 11 → May 24) */
   [
      'ADI-560',
      'Accordion: animate height with CSS grid rows instead of max-height',
      'done',
      4,
      18,
      [7],
      10,
      '16',
      '2026-05-15',
   ],
   [
      'ADI-561',
      'Publish tree-shaking report for the core package',
      'done',
      1,
      0,
      [3, 6],
      null,
      '16',
      '2026-05-12',
   ],
   [
      'ADI-562',
      'Avatar group: overflow counter misreads at exactly max items',
      'done',
      2,
      2,
      [10],
      2,
      '16',
      '2026-05-22',
   ],
   [
      'ADI-563',
      'Fix Switch thumb misalignment in high-contrast mode',
      'done',
      3,
      4,
      [6, 9],
      4,
      '16',
      '2026-05-19',
   ],
   [
      'ADI-564',
      'Document controlled vs uncontrolled patterns for all inputs',
      'done',
      3,
      6,
      [2],
      6,
      '16',
      '2026-05-16',
   ],
   [
      'ADI-565',
      'Breadcrumb: collapse middle items into an ellipsis menu',
      'done',
      4,
      8,
      [9, 1],
      8,
      '16',
      '2026-05-13',
   ],
   [
      'ADI-566',
      'Migrate icon build script to SVGO v4',
      'done',
      1,
      10,
      [5],
      null,
      '16',
      '2026-05-23',
   ],
   [
      'ADI-567',
      'Ship Separator orientation API with responsive variants',
      'shipped',
      2,
      12,
      [1, 4],
      0,
      '16',
      '2026-05-20',
   ],
   [
      'ADI-568',
      'Release Kbd component with platform-aware modifier keys',
      'shipped',
      3,
      14,
      [8],
      2,
      '16',
      '2026-05-17',
   ],
   [
      'ADI-569',
      'Prototype CSS anchor positioning for Tooltip',
      'canceled',
      3,
      16,
      [4, 7],
      4,
      '16',
      '2026-05-14',
   ],
   /* Cycle 17 (completed — May 25 → Jun 7) */
   [
      'ADI-606',
      'Radio group: roving focus skips items rendered in portals',
      'done',
      3,
      14,
      [5],
      6,
      '17',
      '2026-06-05',
   ],
   [
      'ADI-607',
      'Add copy-to-clipboard button to all docs code blocks',
      'done',
      3,
      16,
      [1, 4],
      8,
      '17',
      '2026-06-02',
   ],
   [
      'ADI-608',
      'Progress: indeterminate animation stutters at 120Hz',
      'done',
      4,
      18,
      [8],
      10,
      '17',
      '2026-05-30',
   ],
   [
      'ADI-609',
      'Type Select onValueChange with generic item payloads',
      'done',
      1,
      0,
      [4, 7],
      null,
      '17',
      '2026-05-27',
   ],
   [
      'ADI-610',
      'Scroll area: overlay scrollbar flickers on Windows',
      'done',
      2,
      2,
      [0],
      2,
      '17',
      '2026-06-06',
   ],
   [
      'ADI-611',
      'Add Playwright smoke suite for docs navigation',
      'done',
      3,
      4,
      [7, 10],
      4,
      '17',
      '2026-06-03',
   ],
   [
      'ADI-612',
      'Hover card: separate delay tokens for open and close',
      'done',
      3,
      6,
      [3],
      6,
      '17',
      '2026-05-31',
   ],
   [
      'ADI-613',
      'Normalize the z-index scale across overlay components',
      'done',
      4,
      8,
      [10, 2],
      8,
      '17',
      '2026-05-28',
   ],
   [
      'ADI-614',
      'Ship Textarea auto-resize with min and max rows',
      'shipped',
      1,
      10,
      [6],
      null,
      '17',
      '2026-05-25',
   ],
   [
      'ADI-615',
      'Release Badge dot variant for unread indicators',
      'shipped',
      2,
      12,
      [2, 5],
      0,
      '17',
      '2026-06-04',
   ],
   [
      'ADI-616',
      'Explore Houdini paint worklet for Skeleton shimmer',
      'canceled',
      3,
      14,
      [9],
      2,
      '17',
      '2026-06-01',
   ],
   [
      'ADI-617',
      'Toggle: pressed state lost after form reset',
      'duplicate',
      3,
      16,
      [5, 8],
      4,
      '17',
      '2026-05-29',
   ],
   /* Cycle 18 (completed — Jun 8 → Jun 21) */
   [
      'ADI-627',
      'Menubar: submenu closes when crossing the diagonal safe area',
      'done',
      3,
      17,
      [5],
      9,
      '18',
      '2026-06-15',
   ],
   [
      'ADI-628',
      'Add density prop to Table with compact and comfortable presets',
      'done',
      4,
      19,
      [1],
      11,
      '18',
      '2026-06-12',
   ],
   [
      'ADI-631',
      'Fix Dialog scroll lock leaking padding on nested opens',
      'done',
      2,
      3,
      [4],
      3,
      '18',
      '2026-06-19',
   ],
   [
      'ADI-632',
      'Collapsible: forced reflow when many panels toggle at once',
      'done',
      3,
      5,
      [0],
      null,
      '18',
      '2026-06-16',
   ],
   [
      'ADI-633',
      'Add aria-live announcements to async Combobox results',
      'done',
      3,
      7,
      [7],
      7,
      '18',
      '2026-06-13',
   ],
   [
      'ADI-634',
      'Refactor theme provider to avoid a double render on hydration',
      'done',
      4,
      9,
      [3],
      9,
      '18',
      '2026-06-10',
   ],
   [
      'ADI-635',
      'Pagination: expose sibling and boundary count props',
      'done',
      2,
      11,
      [10],
      11,
      '18',
      '2026-06-20',
   ],
   [
      'ADI-636',
      'Audit focus-visible styles across every interactive component',
      'done',
      2,
      13,
      [6],
      1,
      '18',
      '2026-06-17',
   ],
   [
      'ADI-637',
      'Ship Stepper component with linear and free navigation',
      'shipped',
      3,
      15,
      [2],
      null,
      '18',
      '2026-06-14',
   ],
   [
      'ADI-638',
      'Release the Empty state illustrations pack',
      'shipped',
      3,
      17,
      [9],
      5,
      '18',
      '2026-06-11',
   ],
   [
      'ADI-639',
      'Ship Input OTP with paste and autofill support',
      'shipped',
      4,
      19,
      [5],
      7,
      '18',
      '2026-06-08',
   ],
   [
      'ADI-640',
      'Investigate replacing popper with the native popover API',
      'canceled',
      2,
      1,
      [1],
      9,
      '18',
      '2026-06-18',
   ],
   /* Cycle 19 (completed — Jun 22 → Jul 5) */
   [
      'ADI-647',
      'Tabs: indicator animation desyncs when the tab list wraps',
      'done',
      4,
      9,
      [7],
      5,
      '19',
      '2026-07-03',
   ],
   [
      'ADI-648',
      'Add virtual focus mode to Command menu for screen readers',
      'done',
      2,
      11,
      [3],
      7,
      '19',
      '2026-06-30',
   ],
   [
      'ADI-649',
      'Slider: step markers misplace with non-linear scales',
      'done',
      2,
      13,
      [10],
      9,
      '19',
      '2026-06-27',
   ],
   [
      'ADI-650',
      'Fix Calendar week numbers off by one around DST',
      'done',
      3,
      15,
      [6],
      null,
      '19',
      '2026-06-24',
   ],
   ['ADI-651', 'Add outline and soft variants to Alert', 'done', 3, 17, [2], 1, '19', '2026-07-04'],
   [
      'ADI-652',
      'Reduce Dropdown menu open latency on low-end Android',
      'done',
      4,
      19,
      [9],
      3,
      '19',
      '2026-07-01',
   ],
   [
      'ADI-653',
      'Context menu: long-press support for touch devices',
      'done',
      2,
      1,
      [5],
      5,
      '19',
      '2026-06-28',
   ],
   [
      'ADI-654',
      'Cache the docs search index in a service worker',
      'done',
      2,
      3,
      [1],
      7,
      '19',
      '2026-06-25',
   ],
   [
      'ADI-655',
      'Ship Timeline component with alternating layout',
      'shipped',
      3,
      5,
      [8],
      null,
      '19',
      '2026-06-22',
   ],
   [
      'ADI-656',
      'Release Tag input with paste-splitting and max tags',
      'shipped',
      3,
      7,
      [4],
      11,
      '19',
      '2026-07-02',
   ],
   [
      'ADI-657',
      'Ship Number field with locale-aware formatting',
      'shipped',
      4,
      9,
      [0],
      1,
      '19',
      '2026-06-29',
   ],
   [
      'ADI-658',
      'Drop the IE-era focus polyfill from the bundle',
      'canceled',
      2,
      11,
      [7],
      3,
      '19',
      '2026-06-26',
   ],
   [
      'ADI-659',
      'Rewrite Carousel with scroll snap points only',
      'canceled',
      2,
      13,
      [3],
      5,
      '19',
      '2026-06-23',
   ],
   [
      'ADI-660',
      'Tooltip: content flashes at viewport corners',
      'duplicate',
      3,
      15,
      [10],
      null,
      '19',
      '2026-07-03',
   ],
   /* Cycle 20 (completed — Jul 6 → Jul 19) */
   [
      'ADI-668',
      'Sheet: momentum drag-to-close overshoots on iOS Safari',
      'done',
      3,
      14,
      [3],
      10,
      '20',
      '2026-07-10',
   ],
   [
      'ADI-669',
      'Add row selection checkboxes to the Data grid basic recipe',
      'done',
      3,
      16,
      [10, 2],
      0,
      '20',
      '2026-07-07',
   ],
   [
      'ADI-670',
      'Form: surface server errors next to the matching field',
      'done',
      4,
      18,
      [6],
      2,
      '20',
      '2026-07-17',
   ],
   [
      'ADI-671',
      'Sidebar: persist collapsed sections per workspace',
      'done',
      1,
      0,
      [2, 5],
      null,
      '20',
      '2026-07-14',
   ],
   [
      'ADI-672',
      'Fix Popover flip jitter inside resizable panels',
      'done',
      2,
      2,
      [9],
      6,
      '20',
      '2026-07-11',
   ],
   [
      'ADI-673',
      'Add a keyboard shortcuts cheat sheet to the docs footer',
      'done',
      3,
      4,
      [5, 8],
      8,
      '20',
      '2026-07-08',
   ],
   [
      'ADI-674',
      'Toolbar: overflow menu for actions that do not fit',
      'done',
      3,
      6,
      [1],
      10,
      '20',
      '2026-07-18',
   ],
   [
      'ADI-675',
      'Tree view: async children with loading placeholders',
      'done',
      4,
      8,
      [8, 0],
      0,
      '20',
      '2026-07-15',
   ],
   [
      'ADI-676',
      'Reduce the CSS variable count emitted per theme',
      'done',
      1,
      10,
      [4],
      null,
      '20',
      '2026-07-12',
   ],
   [
      'ADI-677',
      'Add prefers-reduced-motion variants to all animations',
      'done',
      2,
      12,
      [0, 3],
      4,
      '20',
      '2026-07-09',
   ],
   [
      'ADI-678',
      'Ship Rating component with half-star precision',
      'shipped',
      3,
      14,
      [7],
      6,
      '20',
      '2026-07-06',
   ],
   [
      'ADI-679',
      'Release Segmented control with equalized widths',
      'shipped',
      3,
      16,
      [3, 6],
      8,
      '20',
      '2026-07-16',
   ],
   [
      'ADI-680',
      'Spike: WASM-based color contrast checker',
      'canceled',
      4,
      18,
      [10],
      10,
      '20',
      '2026-07-13',
   ],
   [
      'ADI-690',
      'Generate a nightly PDF export of the docs',
      'canceled',
      4,
      19,
      [10],
      3,
      '20',
      '2026-07-16',
   ],
   /* Cycle 21 (current — Jul 20 → Aug 2), batch 2 */
   [
      'ADI-746',
      'Combobox: pin the creatable option row to the list bottom',
      'to-do',
      3,
      6,
      [6],
      6,
      '21',
      '2026-07-29',
      '2026-08-11',
   ],
   [
      'ADI-747',
      'Add a drag handle affordance to sortable Table rows',
      'to-do',
      4,
      8,
      [2, 5],
      8,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-748',
      'Date picker: range preset shortcuts panel',
      'to-do',
      1,
      10,
      [9],
      null,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-749',
      'Expose an onOpenAutoFocus escape hatch on Drawer',
      'to-do',
      2,
      12,
      [5, 8],
      0,
      '21',
      '2026-07-20',
      '2026-07-29',
   ],
   [
      'ADI-750',
      'Add loading prop to Button with spinner replacement',
      'to-do',
      3,
      14,
      [1],
      2,
      '21',
      '2026-07-30',
   ],
   [
      'ADI-751',
      'Tabs: lazy mount panels with a keepMounted opt-in',
      'to-do',
      3,
      16,
      [8, 0],
      4,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-752',
      'Checkbox: polish the indeterminate-to-checked animation',
      'to-do',
      4,
      18,
      [4],
      6,
      '21',
      '2026-07-24',
      '2026-08-08',
   ],
   [
      'ADI-753',
      'Publish theming recipes for brand palette import',
      'to-do',
      1,
      0,
      [0, 3],
      null,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-754',
      'Add a sticky footer slot to Dialog for long forms',
      'to-do',
      2,
      2,
      [7],
      10,
      '21',
      '2026-07-31',
   ],
   [
      'ADI-755',
      'Navigation menu: viewport-aware submenu alignment',
      'to-do',
      3,
      4,
      [3, 6],
      0,
      '21',
      '2026-07-28',
      '2026-08-08',
   ],
   [
      'ADI-756',
      'Add a copy button to color token swatches in docs',
      'to-do',
      3,
      6,
      [10],
      2,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-757',
      'File upload: directory drop with entries traversal',
      'to-do',
      4,
      8,
      [6, 9],
      4,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-758',
      'Add aria-description support to the form field wrapper',
      'to-do',
      1,
      10,
      [2],
      null,
      '21',
      '2026-08-01',
      '2026-08-08',
   ],
   [
      'ADI-759',
      'Toast: action button variant with destructive intent',
      'to-do',
      2,
      12,
      [9, 1],
      8,
      '21',
      '2026-07-29',
   ],
   [
      'ADI-760',
      'Scroll area: scroll shadows via scroll-driven animations',
      'to-do',
      3,
      14,
      [5],
      10,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-761',
      'Add a monospace numeric variant to Table cells',
      'to-do',
      3,
      16,
      [1, 4],
      0,
      '21',
      '2026-07-23',
      '2026-08-05',
   ],
   [
      'ADI-762',
      'Command menu: recent items section with local ranking',
      'to-do',
      4,
      18,
      [8],
      2,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-763',
      'Avatar: fallback gradient derived from the user id hash',
      'to-do',
      1,
      0,
      [4, 7],
      null,
      '21',
      '2026-07-30',
   ],
   [
      'ADI-764',
      'Input: leading and trailing addon composition API',
      'to-do',
      2,
      2,
      [0],
      6,
      '21',
      '2026-07-27',
      '2026-08-05',
   ],
   [
      'ADI-765',
      'Add a skip-to-content link helper for app shells',
      'to-do',
      3,
      4,
      [7, 10],
      8,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-766',
      'Popover: opt-in modal mode with focus containment',
      'to-do',
      3,
      6,
      [3],
      10,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-767',
      'Breadcrumb: schema.org structured data helper',
      'to-do',
      4,
      8,
      [10, 2],
      0,
      '21',
      '2026-07-31',
      '2026-08-15',
   ],
   [
      'ADI-768',
      'Document SSR streaming caveats for overlay components',
      'to-do',
      1,
      10,
      [6],
      null,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-769',
      'Add container query helpers to layout primitives',
      'to-do',
      2,
      12,
      [2, 5],
      4,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-770',
      'Kanban recipe: column virtualization for long boards',
      'to-do',
      3,
      14,
      [9],
      6,
      '21',
      '2026-07-22',
      '2026-08-02',
   ],
   [
      'ADI-771',
      'Data grid: column pinning with shadow separators',
      'in-progress',
      3,
      16,
      [5, 8],
      8,
      '21',
      '2026-08-01',
   ],
   [
      'ADI-772',
      'Migrate the docs playground to Sandpack 3',
      'in-progress',
      4,
      18,
      [1],
      10,
      '21',
      '2026-07-29',
   ],
   [
      'ADI-773',
      'Calendar: multi-month view with linked navigation',
      'in-progress',
      1,
      0,
      [8, 0],
      null,
      '21',
      '2026-07-26',
      '2026-08-02',
   ],
   [
      'ADI-774',
      'Refactor Select to composable item slots',
      'in-progress',
      2,
      2,
      [4],
      2,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-775',
      'Add RTL flip audit tooling to CI',
      'in-progress',
      3,
      4,
      [0, 3],
      4,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-776',
      'Theme editor: live preview across the component gallery',
      'in-progress',
      3,
      6,
      [7],
      6,
      '21',
      '2026-07-30',
      '2026-08-12',
   ],
   [
      'ADI-777',
      'Form: async validators with debounce and abort',
      'in-progress',
      4,
      8,
      [3, 6],
      8,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-778',
      'Tree view: type-ahead search across expanded nodes',
      'in-progress',
      1,
      10,
      [10],
      null,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-779',
      'Charts recipe: themable sparkline primitives',
      'in-progress',
      2,
      12,
      [6, 9],
      0,
      '21',
      '2026-07-21',
      '2026-07-30',
   ],
   [
      'ADI-780',
      'Dialog: inert background instead of the aria-hidden walker',
      'technical-review',
      3,
      14,
      [2],
      2,
      '21',
      '2026-07-31',
   ],
   [
      'ADI-781',
      'Slider: pointer capture strategy for nested scroll',
      'technical-review',
      3,
      16,
      [9, 1],
      4,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-782',
      'Replace lodash.debounce with an in-house scheduler',
      'technical-review',
      4,
      18,
      [5],
      6,
      '21',
      '2026-07-25',
      '2026-08-09',
   ],
   [
      'ADI-783',
      'Combobox: windowed list rendering above 1k options',
      'technical-review',
      1,
      0,
      [1, 4],
      null,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-784',
      'Tokens: semantic alias layer between core and components',
      'technical-review',
      2,
      2,
      [8],
      10,
      '21',
      '2026-08-01',
   ],
   [
      'ADI-785',
      'Menubar: macOS-style key glyph rendering',
      'paused',
      3,
      4,
      [4, 7],
      0,
      '21',
      '2026-07-29',
      '2026-08-09',
   ],
   [
      'ADI-786',
      'Drawer: snap points with velocity-based settle',
      'paused',
      3,
      6,
      [0],
      2,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-787',
      'Upgrade to Tailwind v4.1 once the oxide bug is fixed upstream',
      'blocked',
      4,
      8,
      [7, 10],
      4,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-788',
      'Date picker: Temporal adoption blocked on polyfill size',
      'blocked',
      1,
      10,
      [3],
      null,
      '21',
      '2026-07-20',
      '2026-07-27',
   ],
   [
      'ADI-789',
      'Popover: waiting on an upstream fix for iOS visualViewport drift',
      'blocked',
      2,
      12,
      [10, 2],
      8,
      '21',
      '2026-07-30',
   ],
   [
      'ADI-790',
      'Select: users expect typing to jump across option groups',
      'product-feedback',
      3,
      14,
      [6],
      10,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-791',
      'Toast: stacking order feels inverted when many fire at once',
      'product-feedback',
      3,
      16,
      [2, 5],
      0,
      '21',
      '2026-07-24',
      '2026-08-06',
   ],
   [
      'ADI-792',
      'Sidebar: resize handle is too narrow to grab on trackpads',
      'product-feedback',
      4,
      18,
      [9],
      2,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-793',
      'Data grid: header menu discoverability is low in testing',
      'product-feedback',
      1,
      0,
      [5, 8],
      null,
      '21',
      '2026-07-31',
   ],
   [
      'ADI-794',
      'Report: Tooltip stays open after a drag starts from the trigger',
      'triage',
      0,
      null,
      [1],
      6,
      '21',
      '2026-07-28',
      '2026-08-06',
   ],
   [
      'ADI-795',
      'Report: Tabs panel scroll position resets on theme switch',
      'triage',
      0,
      null,
      [8, 0],
      8,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-796',
      'Fix Combobox popover width when the trigger sits in a grid cell',
      'done',
      3,
      6,
      [4],
      10,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-797',
      'Button: gap collapses when an icon-only child is conditional',
      'done',
      4,
      8,
      [0, 3],
      0,
      '21',
      '2026-08-01',
      '2026-08-16',
   ],
   [
      'ADI-798',
      'Toast region announces politely instead of assertively',
      'done',
      1,
      10,
      [7],
      null,
      '21',
      '2026-07-29',
   ],
   [
      'ADI-799',
      'Card: consistent padding scale across media and body slots',
      'done',
      2,
      12,
      [3, 6],
      4,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-900',
      'Fix Slider keyboard step with fractional precision',
      'done',
      3,
      14,
      [8],
      10,
      '21',
      '2026-07-29',
   ],
   [
      'ADI-901',
      'Dropdown: checkbox item icon alignment in RTL',
      'done',
      3,
      16,
      [4, 7],
      0,
      '21',
      '2026-07-26',
      '2026-08-08',
   ],
   [
      'ADI-902',
      'Docs: version switcher for component API tables',
      'done',
      4,
      18,
      [0],
      2,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-903',
      'Fix Sheet header truncation with long titles',
      'done',
      1,
      0,
      [7, 10],
      null,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-904',
      'Radio group: card-style items recipe',
      'done',
      2,
      2,
      [3],
      6,
      '21',
      '2026-07-30',
      '2026-08-08',
   ],
   [
      'ADI-905',
      'Reduce the hydration payload of the theme script by inlining',
      'done',
      3,
      4,
      [10, 2],
      8,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-906',
      'Fix Calendar disabled matcher for date ranges',
      'done',
      3,
      6,
      [6],
      10,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-907',
      'Skeleton: match the line-height rhythm of Text presets',
      'done',
      4,
      8,
      [2, 5],
      0,
      '21',
      '2026-07-21',
      '2026-08-05',
   ],
   [
      'ADI-908',
      'Tabs: Home and End keys jump to the first and last tab',
      'done',
      1,
      10,
      [9],
      null,
      '21',
      '2026-07-31',
   ],
   [
      'ADI-909',
      'Fix Dialog title id collision with multiple instances',
      'done',
      2,
      12,
      [5, 8],
      4,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-910',
      'Command menu: Escape closes nested pages before the dialog',
      'done',
      3,
      14,
      [1],
      6,
      '21',
      '2026-07-25',
      '2026-08-05',
   ],
   [
      'ADI-911',
      'Search docs by prop name and enum values',
      'done',
      3,
      16,
      [8, 0],
      8,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-912',
      'Fix Progress label rounding at 99.5 percent',
      'done',
      4,
      18,
      [4],
      10,
      '21',
      '2026-08-01',
   ],
   [
      'ADI-913',
      'Stepper: clamp orientation changes during a transition',
      'done',
      1,
      0,
      [0, 3],
      null,
      '21',
      '2026-07-29',
      '2026-08-05',
   ],
   [
      'ADI-914',
      'Ship Spinner with size and stroke tokens',
      'shipped',
      2,
      2,
      [7],
      2,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-915',
      'Release the Resizable panels persistence adapter',
      'shipped',
      3,
      4,
      [3, 6],
      4,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-916',
      'Ship the Toolbar overflow priority API',
      'shipped',
      3,
      6,
      [10],
      6,
      '21',
      '2026-07-20',
      '2026-08-02',
   ],
   [
      'ADI-917',
      'Release the dark mode contrast pass for all charts',
      'shipped',
      4,
      8,
      [6, 9],
      8,
      '21',
      '2026-07-30',
   ],
   [
      'ADI-918',
      'Inline critical CSS experiment for the docs home',
      'canceled',
      1,
      10,
      [2],
      null,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-919',
      'Custom scrollbar styling fallback for Firefox',
      'canceled',
      2,
      12,
      [9, 1],
      0,
      '21',
      '2026-07-24',
      '2026-08-02',
   ],
   /* Cycle 22 (upcoming — Aug 3 → Aug 16), batch 2 */
   [
      'ADI-920',
      'Combobox: multi-select chips inside the trigger',
      'to-do',
      3,
      14,
      [5],
      2,
      '22',
      '2026-07-25',
   ],
   [
      'ADI-921',
      'Data grid: row grouping with aggregate footers',
      'to-do',
      3,
      16,
      [1, 4],
      4,
      '22',
      '2026-08-04',
   ],
   [
      'ADI-922',
      'Calendar: natural language date input parsing',
      'to-do',
      4,
      18,
      [8],
      6,
      '22',
      '2026-08-01',
      '2026-08-16',
   ],
   [
      'ADI-923',
      'Theme: ship a first-class high-contrast preset',
      'to-do',
      1,
      0,
      [4, 7],
      null,
      '22',
      '2026-07-29',
   ],
   [
      'ADI-924',
      'Form: field array helpers with stable keys',
      'to-do',
      2,
      2,
      [0],
      10,
      '22',
      '2026-07-26',
   ],
   [
      'ADI-925',
      'Command menu: plugin API for external providers',
      'to-do',
      3,
      4,
      [7, 10],
      0,
      '22',
      '2026-08-05',
      '2026-08-16',
   ],
   [
      'ADI-926',
      'Table: sticky first column with horizontal scroll hints',
      'to-do',
      3,
      6,
      [3],
      2,
      '22',
      '2026-08-02',
   ],
   [
      'ADI-927',
      'Toast: cross-tab dedupe via BroadcastChannel',
      'to-do',
      4,
      8,
      [10, 2],
      4,
      '22',
      '2026-07-30',
   ],
   [
      'ADI-928',
      'Docs: interactive accessibility annotations overlay',
      'to-do',
      1,
      10,
      [6],
      null,
      '22',
      '2026-07-27',
      '2026-08-03',
   ],
   [
      'ADI-929',
      'File upload: resumable chunked uploads recipe',
      'to-do',
      2,
      12,
      [2, 5],
      8,
      '22',
      '2026-07-24',
   ],
   [
      'ADI-930',
      'Tabs: draggable reorder with an overflow scroller',
      'to-do',
      3,
      14,
      [9],
      10,
      '22',
      '2026-08-03',
   ],
   [
      'ADI-931',
      'Sidebar: nested collapsible groups with rail mode',
      'to-do',
      3,
      16,
      [5, 8],
      0,
      '22',
      '2026-07-31',
      '2026-08-13',
   ],
   [
      'ADI-932',
      'Navigation menu: mega menu grid recipe',
      'to-do',
      4,
      18,
      [1],
      2,
      '22',
      '2026-07-28',
   ],
   [
      'ADI-933',
      'Icons: per-icon dynamic import codemod',
      'to-do',
      1,
      0,
      [8, 0],
      null,
      '22',
      '2026-07-25',
   ],
   [
      'ADI-934',
      'Timeline: virtualized rendering for 1k+ events',
      'paused',
      2,
      2,
      [4],
      6,
      '22',
      '2026-08-04',
      '2026-08-13',
   ],
   [
      'ADI-935',
      'Tokens: cross-brand theming pipeline',
      'paused',
      3,
      4,
      [0, 3],
      8,
      '22',
      '2026-08-01',
   ],
   /* Backlog stock, batch 2 (no cycle) */
   ['ADI-822', 'Add a Masonry layout primitive', 'backlog', 2, 12, [4, 7], 4, '', '2026-03-09'],
   [
      'ADI-823',
      'Print stylesheet pass for the docs pages',
      'backlog',
      3,
      null,
      [0],
      6,
      '',
      '2026-03-06',
   ],
   [
      'ADI-824',
      'Color picker component with the EyeDropper API',
      'backlog',
      3,
      16,
      [7, 10],
      8,
      '',
      '2026-03-03',
   ],
   [
      'ADI-825',
      'Add a Gantt chart recipe on top of the Data grid',
      'backlog',
      4,
      18,
      [3],
      10,
      '',
      '2026-03-13',
   ],
   [
      'ADI-826',
      'Offline-first docs with background sync',
      'backlog',
      1,
      null,
      [10, 2],
      null,
      '',
      '2026-03-10',
   ],
   [
      'ADI-827',
      'Add a Transfer list component for bulk assignment',
      'backlog',
      2,
      2,
      [6],
      2,
      '',
      '2026-03-07',
   ],
   [
      'ADI-828',
      'Signature pad input with pointer smoothing',
      'backlog',
      3,
      4,
      [2, 5],
      4,
      '',
      '2026-03-04',
   ],
   [
      'ADI-829',
      'Mention and hashtag tokens for Textarea',
      'backlog',
      3,
      null,
      [9],
      6,
      '',
      '2026-03-14',
   ],
   [
      'ADI-830',
      'Add an Org chart recipe with collapsible branches',
      'backlog',
      4,
      8,
      [5, 8],
      8,
      '',
      '2026-03-11',
   ],
   [
      'ADI-831',
      'Keyboard-only usage guide with interactive drills',
      'backlog',
      1,
      10,
      [1],
      null,
      '',
      '2026-03-08',
   ],
   [
      'ADI-832',
      'Add a Diff viewer component for code review flows',
      'backlog',
      2,
      null,
      [8, 0],
      0,
      '',
      '2026-03-05',
   ],
   [
      'ADI-833',
      'Currency input with Intl number parts editing',
      'backlog',
      3,
      14,
      [4],
      2,
      '',
      '2026-03-02',
   ],
   [
      'ADI-834',
      'Add a Split button with default action memory',
      'backlog',
      3,
      16,
      [0, 3],
      4,
      '',
      '2026-03-12',
   ],
   [
      'ADI-835',
      'Heatmap calendar recipe for activity views',
      'backlog',
      4,
      null,
      [7],
      6,
      '',
      '2026-03-09',
   ],
   [
      'ADI-836',
      'Add a Dock component with magnification easing',
      'backlog',
      1,
      0,
      [3, 6],
      null,
      '',
      '2026-03-06',
   ],
   [
      'ADI-837',
      'Video player controls skin over media chrome',
      'backlog',
      2,
      2,
      [10],
      10,
      '',
      '2026-03-03',
   ],
   [
      'ADI-838',
      'Add onboarding coach marks with anchored steps',
      'backlog',
      3,
      null,
      [6, 9],
      0,
      '',
      '2026-03-13',
   ],
   [
      'ADI-839',
      'CSV import wizard recipe with column mapping',
      'backlog',
      3,
      6,
      [2],
      2,
      '',
      '2026-03-10',
   ],
   [
      'ADI-840',
      'Add a Chat message list with day separators',
      'backlog',
      4,
      8,
      [9, 1],
      4,
      '',
      '2026-03-07',
   ],
   [
      'ADI-841',
      'PWA install prompt pattern for the docs demo apps',
      'backlog',
      1,
      null,
      [5],
      null,
      '',
      '2026-03-04',
   ],
   [
      'ADI-842',
      'Add a Notification center panel with grouped digests',
      'backlog',
      2,
      12,
      [1, 4],
      8,
      '',
      '2026-03-14',
   ],
   [
      'ADI-843',
      'Map input recipe with a geocoding adapter',
      'backlog',
      3,
      14,
      [8],
      10,
      '',
      '2026-03-11',
   ],
   [
      'ADI-844',
      'AI-assisted prop suggestions in the playground',
      'idea',
      0,
      null,
      [4, 7],
      null,
      '',
      '2026-03-08',
   ],
   [
      'ADI-845',
      'Voice control map for common component actions',
      'idea',
      0,
      18,
      [0],
      null,
      '',
      '2026-03-05',
   ],
   [
      'ADI-846',
      'Generate a theme from a single brand color via APCA',
      'idea',
      0,
      0,
      [7, 10],
      null,
      '',
      '2026-03-02',
   ],
   [
      'ADI-847',
      'Haptic feedback hooks for mobile web interactions',
      'idea',
      0,
      null,
      [3],
      null,
      '',
      '2026-03-12',
   ],
   [
      'ADI-848',
      'Ambient mode: reduce chrome when the user is idle',
      'idea',
      0,
      4,
      [10, 2],
      null,
      '',
      '2026-03-09',
   ],
   [
      'ADI-849',
      'Per-component carbon cost estimates in the docs',
      'idea',
      0,
      6,
      [6],
      null,
      '',
      '2026-03-06',
   ],
   [
      'ADI-850',
      'Live cursors in the docs playground for pairing',
      'idea',
      0,
      null,
      [2, 5],
      null,
      '',
      '2026-03-03',
   ],
   [
      'ADI-851',
      'Sound design tokens for optional UI audio cues',
      'idea',
      0,
      10,
      [9],
      null,
      '',
      '2026-03-13',
   ],
   [
      'ADI-852',
      'Auto-generate visual regression baselines from Figma',
      'idea',
      0,
      12,
      [5, 8],
      null,
      '',
      '2026-03-10',
   ],
   [
      'ADI-853',
      'Component usage analytics opt-in for design system teams',
      'idea',
      0,
      null,
      [1],
      null,
      '',
      '2026-03-07',
   ],
   [
      'ADI-854',
      'Report: Select popover misaligns inside CSS zoom containers',
      'triage',
      0,
      null,
      [8, 0],
      8,
      '',
      '2026-03-04',
   ],
   [
      'ADI-855',
      'Report: Dialog close animation janks with backdrop blur',
      'triage',
      0,
      null,
      [4],
      10,
      '',
      '2026-03-14',
   ],
   [
      'ADI-856',
      'Report: Combobox filter breaks with diacritics in options',
      'triage',
      0,
      null,
      [0, 3],
      null,
      '',
      '2026-03-11',
   ],
   [
      'ADI-857',
      'Report: Slider thumb escapes the track in scaled iframes',
      'triage',
      0,
      null,
      [7],
      2,
      '',
      '2026-03-08',
   ],
   [
      'ADI-858',
      'Report: Tabs keyboard loop breaks with hidden tabs',
      'triage',
      0,
      null,
      [3, 6],
      4,
      '',
      '2026-03-05',
   ],
   [
      'ADI-859',
      'Report: Toast swipe conflicts with horizontal page scroll',
      'triage',
      0,
      null,
      [10],
      6,
      '',
      '2026-03-02',
   ],
   [
      'ADI-860',
      'Report: Tooltip arrow renders behind content on Safari 17',
      'triage',
      0,
      null,
      [6, 9],
      8,
      '',
      '2026-03-12',
   ],
   [
      'ADI-861',
      'Report: Data grid resize cursor sticks after mouseup',
      'triage',
      0,
      null,
      [2],
      null,
      '',
      '2026-03-09',
   ],
   [
      'ADI-862',
      'Report: Date picker locale prop ignored for aria labels',
      'triage',
      0,
      null,
      [9, 1],
      0,
      '',
      '2026-03-06',
   ],
   [
      'ADI-863',
      'Report: Sidebar rail tooltip overlaps the window controls',
      'triage',
      0,
      null,
      [5],
      2,
      '',
      '2026-03-03',
   ],
];

/* -------------------------------------------------------------------------- */
/*                                   Ranks                                    */
/* -------------------------------------------------------------------------- */

// Generates issue ranks using the LexoRank algorithm.
export const ranks: string[] = [];
const generateIssuesRanks = () => {
   const firstRank = new LexoRank('a3c');
   ranks.push(firstRank.toString());
   for (let i = 1; i < seeds.length + 20; i++) {
      const previousRank = LexoRank.from(ranks[i - 1]);
      ranks.push(previousRank.increment().toString());
   }
};
generateIssuesRanks();

/* -------------------------------------------------------------------------- */
/*                                   Issues                                   */
/* -------------------------------------------------------------------------- */

export const issues: Issue[] = seeds.map((seed, index) => {
   const [
      identifier,
      title,
      statusId,
      priorityIdx,
      assigneeIdx,
      labelIdxs,
      projectIdx,
      cycleId,
      createdAt,
      dueDate,
   ] = seed;

   return {
      id: String(index + 1),
      identifier,
      title,
      description: '',
      status: statusById(statusId),
      priority: priorities[priorityIdx],
      assignee: assigneeIdx === null ? null : (users[assigneeIdx] ?? null),
      labels: labelIdxs.map((i) => labels[i]).filter(Boolean),
      project: projectIdx === null ? undefined : projects[projectIdx],
      cycleId,
      createdAt,
      rank: ranks[index],
      ...(dueDate ? { dueDate } : {}),
   };
});

/* -------------------------------------------------------------------------- */
/*                                  Helpers                                   */
/* -------------------------------------------------------------------------- */

export function groupIssuesByStatus(issues: Issue[]): Record<string, Issue[]> {
   return issues.reduce<Record<string, Issue[]>>((acc, issue) => {
      const statusId = issue.status.id;

      if (!acc[statusId]) {
         acc[statusId] = [];
      }

      acc[statusId].push(issue);

      return acc;
   }, {});
}

export function sortIssuesByPriority(issues: Issue[]): Issue[] {
   const priorityOrder: Record<string, number> = {
      'urgent': 0,
      'high': 1,
      'medium': 2,
      'low': 3,
      'no-priority': 4,
   };

   return issues
      .slice()
      .sort(
         (a, b) =>
            priorityOrder[a.priority.id as keyof typeof priorityOrder] -
            priorityOrder[b.priority.id as keyof typeof priorityOrder]
      );
}

export function filterIssuesByCycle(allIssues: Issue[], cycleId: string): Issue[] {
   return allIssues.filter((issue) => issue.cycleId === cycleId);
}

export function filterIssuesByCategories(
   allIssues: Issue[],
   categories: StatusCategory[]
): Issue[] {
   return allIssues.filter((issue) => categories.includes(issue.status.category));
}

/**
 * Deterministic pseudo-creator for an issue (mock data has no author field).
 * Used by the member profile "Created" tab.
 */
export function issueCreatorIndex(issue: Issue, memberCount: number): number {
   let hash = 0;
   for (let i = 0; i < issue.identifier.length; i++) {
      hash = (hash * 31 + issue.identifier.charCodeAt(i)) >>> 0;
   }
   return hash % memberCount;
}
