import { LexoRank } from '@/lib/utils';
import { LabelInterface, labels } from './labels';
import { Priority, priorities } from './priorities';
import { Project, projects } from './projects';
import { Status, status, StatusCategory } from './status';
import { User, users } from './users';

export interface Issue {
   id: string;
   identifier: string;
   title: string;
   description: string;
   status: Status;
   assignee: User | null;
   priority: Priority;
   labels: LabelInterface[];
   createdAt: string;
   /** Cycle the issue belongs to. Empty string = no cycle (backlog stock). */
   cycleId: string;
   project?: Project;
   subissues?: string[];
   rank: string;
   dueDate?: string;
}

/* -------------------------------------------------------------------------- */
/*                             Seed-based generation                          */
/* -------------------------------------------------------------------------- */

const statusById = (id: string): Status => {
   const found = status.find((s) => s.id === id);
   if (!found) throw new Error(`Unknown status id: ${id}`);
   return found;
};

/**
 * Compact issue seed:
 * [identifier, title, statusId, priorityIdx, assigneeIdx | null, labelIdxs, projectIdx | null, cycleId, createdAt, dueDate?]
 *
 * - priorityIdx: index in `priorities` (0 no-priority, 1 urgent, 2 high, 3 medium, 4 low)
 * - assigneeIdx / labelIdxs / projectIdx: indexes in `users` / `labels` / `projects`
 * - cycleId: '' = not planned in any cycle
 */
type IssueSeed = [
   string,
   string,
   string,
   number,
   number | null,
   number[],
   number | null,
   string,
   string,
   string?,
];

const seeds: IssueSeed[] = [
   /* ------------------------- Cycle 21 (current) ------------------------- */
   // Product Feedback (2)
   [
      'ADI-701',
      'Combobox: keyboard selection skips disabled options inconsistently',
      'product-feedback',
      2,
      0,
      [0, 8],
      0,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-702',
      'Date picker: month navigation feels laggy on low-end devices',
      'product-feedback',
      3,
      6,
      [5],
      9,
      '21',
      '2026-07-22',
   ],
   // In Progress (4)
   [
      'ADI-703',
      'Rework Dialog focus trap to support nested portals',
      'in-progress',
      1,
      2,
      [1, 8],
      2,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-704',
      'Add virtualization to Data Table for 10k+ rows',
      'in-progress',
      2,
      4,
      [5],
      9,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-705',
      'Ship CLI flag to scaffold components with test files',
      'in-progress',
      3,
      8,
      [2, 9],
      5,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-706',
      'Migrate color tokens to OKLCH with fallbacks',
      'in-progress',
      2,
      12,
      [4],
      1,
      '21',
      '2026-07-24',
   ],
   // Technical Review (2)
   [
      'ADI-707',
      'Refactor Tooltip positioning engine to floating middleware',
      'technical-review',
      2,
      1,
      [4],
      7,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-708',
      'Toast queue: collapse duplicate notifications',
      'technical-review',
      3,
      10,
      [2],
      11,
      '21',
      '2026-07-22',
   ],
   // Paused (1)
   [
      'ADI-709',
      'Carousel: momentum scrolling on trackpads',
      'paused',
      4,
      14,
      [2],
      0,
      '21',
      '2026-07-21',
   ],
   // Blocked (1)
   [
      'ADI-710',
      'Command palette: async sources hang when provider throws',
      'blocked',
      1,
      3,
      [1],
      0,
      '21',
      '2026-07-25',
   ],
   // Triage (1)
   [
      'ADI-711',
      'Report: Select dropdown clipped inside scrollable Sheet',
      'triage',
      0,
      null,
      [1],
      null,
      '21',
      '2026-07-30',
   ],
   // Todo (13)
   [
      'ADI-712',
      'Add skeleton variants for Card and Table',
      'to-do',
      3,
      5,
      [0],
      6,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-713',
      'Expose CSS variables for Radix Accordion animations',
      'to-do',
      4,
      null,
      [0],
      0,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-714',
      'Breadcrumb: support collapsed middle items with popover',
      'to-do',
      3,
      7,
      [2],
      3,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-715',
      'Form: surface async validation state on submit button',
      'to-do',
      2,
      9,
      [10],
      10,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-716',
      'Avatar group: overflow counter with tooltip listing users',
      'to-do',
      4,
      11,
      [2],
      6,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-717',
      'Number input: locale-aware decimal separators',
      'to-do',
      3,
      13,
      [10],
      10,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-718',
      'Docs: interactive playground for Badge variants',
      'to-do',
      4,
      15,
      [3],
      1,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-719',
      'Resizable panels: persist layout per page in memory',
      'to-do',
      3,
      16,
      [2],
      4,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-720',
      'Tabs: add vertical orientation with proper roving focus',
      'to-do',
      2,
      17,
      [8],
      0,
      '21',
      '2026-07-27',
   ],
   [
      'ADI-721',
      'Progress: indeterminate state with reduced-motion fallback',
      'to-do',
      4,
      18,
      [8],
      11,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-722',
      'Chart palette: colorblind-safe categorical scale',
      'to-do',
      2,
      19,
      [8, 6],
      4,
      '21',
      '2026-07-29',
   ],
   [
      'ADI-723',
      'Sidebar: double-click on rail to collapse to icons',
      'to-do',
      4,
      0,
      [2],
      5,
      '21',
      '2026-07-30',
   ],
   [
      'ADI-724',
      'Dropdown: sub-menu opens off-screen near viewport edge',
      'to-do',
      2,
      null,
      [1],
      8,
      '21',
      '2026-07-31',
   ],
   // Done (10)
   [
      'ADI-725',
      'Fix Switch thumb misalignment in RTL layouts',
      'done',
      2,
      2,
      [1],
      10,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-726',
      'Memoize Table row renderer to cut re-renders by 60%',
      'done',
      1,
      4,
      [5],
      9,
      '21',
      '2026-07-20',
   ],
   [
      'ADI-727',
      'Add aria-live region to inline form errors',
      'done',
      2,
      6,
      [8, 10],
      10,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-728',
      'Popover: flip to top when bottom space is insufficient',
      'done',
      3,
      8,
      [1],
      7,
      '21',
      '2026-07-21',
   ],
   [
      'ADI-729',
      'Theme switcher: persist preference and honor system change',
      'done',
      3,
      10,
      [2],
      1,
      '21',
      '2026-07-22',
   ],
   [
      'ADI-730',
      'Slider: snap points with haptic-like visual ticks',
      'done',
      4,
      12,
      [2],
      10,
      '21',
      '2026-07-23',
   ],
   [
      'ADI-731',
      'Docs search: index component prop tables',
      'done',
      3,
      14,
      [3],
      3,
      '21',
      '2026-07-24',
   ],
   [
      'ADI-732',
      'Checkbox: indeterminate propagation for nested lists',
      'done',
      2,
      16,
      [2],
      10,
      '21',
      '2026-07-25',
   ],
   [
      'ADI-733',
      'Reduce icon bundle size with per-icon entrypoints',
      'done',
      2,
      18,
      [5],
      5,
      '21',
      '2026-07-26',
   ],
   [
      'ADI-734',
      'Calendar: highlight today with subtle ring in dark mode',
      'done',
      4,
      1,
      [6],
      9,
      '21',
      '2026-07-27',
   ],
   // Shipped (2)
   [
      'ADI-735',
      'Release Empty State component with illustration slots',
      'shipped',
      3,
      3,
      [2],
      6,
      '21',
      '2026-07-28',
   ],
   [
      'ADI-736',
      'Publish v2.4 with tree-shakable exports',
      'shipped',
      1,
      5,
      [5, 2],
      5,
      '21',
      '2026-07-29',
   ],
   // Canceled (1)
   [
      'ADI-737',
      'Prototype parallax hero for docs landing',
      'canceled',
      4,
      7,
      [6],
      3,
      '21',
      '2026-07-30',
   ],

   /* ------------------------ Cycle 22 (upcoming) ------------------------- */
   [
      'ADI-738',
      'Timeline component: draft API and anatomy',
      'to-do',
      2,
      9,
      [2, 6],
      6,
      '22',
      '2026-07-26',
   ],
   [
      'ADI-739',
      'File upload: chunked uploads with resumable state',
      'to-do',
      2,
      11,
      [2],
      10,
      '22',
      '2026-07-27',
   ],
   [
      'ADI-740',
      'Kbd component: platform-aware modifier rendering',
      'to-do',
      4,
      13,
      [0],
      0,
      '22',
      '2026-07-28',
   ],
   [
      'ADI-741',
      'Stepper: validate steps lazily on next',
      'to-do',
      3,
      15,
      [10],
      10,
      '22',
      '2026-07-29',
   ],
   [
      'ADI-742',
      'Density mode: compact spacing scale across components',
      'to-do',
      3,
      17,
      [0, 6],
      1,
      '22',
      '2026-07-30',
   ],
   [
      'ADI-743',
      'Docs: migration guide from v1 tokens to v2 tokens',
      'to-do',
      3,
      19,
      [3],
      3,
      '22',
      '2026-07-31',
   ],
   [
      'ADI-744',
      'Audit Dialog scroll locking on iOS Safari',
      'paused',
      2,
      0,
      [1, 8],
      2,
      '22',
      '2026-07-25',
   ],
   [
      'ADI-745',
      'Benchmark charts rendering vs. canvas fallback',
      'paused',
      3,
      2,
      [5],
      4,
      '22',
      '2026-07-26',
   ],

   /* ----------------------- Cycle 20 (completed) ------------------------- */
   [
      'ADI-681',
      'Add copy-to-clipboard button to code blocks in docs',
      'done',
      3,
      4,
      [3],
      3,
      '20',
      '2026-07-06',
   ],
   ['ADI-682', 'Fix Tabs indicator jump on font load', 'done', 2, 6, [1], 0, '20', '2026-07-07'],
   [
      'ADI-683',
      'Ship Combobox multi-select with tag input',
      'shipped',
      2,
      8,
      [2],
      10,
      '20',
      '2026-07-09',
   ],
   [
      'ADI-684',
      'Contrast pass on muted foreground colors',
      'done',
      2,
      10,
      [8],
      1,
      '20',
      '2026-07-11',
   ],
   [
      'ADI-685',
      'Table sticky header shadow only when scrolled',
      'done',
      4,
      12,
      [0],
      9,
      '20',
      '2026-07-13',
   ],
   [
      'ADI-686',
      'Deprecate legacy Grid in favor of layout primitives',
      'canceled',
      3,
      14,
      [4],
      6,
      '20',
      '2026-07-15',
   ],
   [
      'ADI-687',
      'Snapshot tests for all Badge permutations',
      'done',
      4,
      16,
      [9],
      6,
      '20',
      '2026-07-17',
   ],

   /* ----------------------- Cycle 19 (completed) ------------------------- */
   [
      'ADI-661',
      'Rewrite Tooltip docs with do/don’t examples',
      'done',
      3,
      1,
      [3],
      7,
      '19',
      '2026-06-22',
   ],
   [
      'ADI-662',
      'Fix focus ring clipped by overflow-hidden cards',
      'done',
      2,
      3,
      [1, 8],
      6,
      '19',
      '2026-06-24',
   ],
   ['ADI-663', 'Ship Sonner-based toast presets', 'shipped', 3, 5, [2], 11, '19', '2026-06-26'],
   ['ADI-664', 'Lazy-load heavy demos on docs pages', 'done', 2, 7, [5], 3, '19', '2026-06-28'],
   [
      'ADI-665',
      'Select: type-ahead across grouped options',
      'done',
      3,
      9,
      [2],
      8,
      '19',
      '2026-06-30',
   ],
   [
      'ADI-666',
      'Duplicate of ADI-662 reported from support',
      'duplicate',
      0,
      null,
      [1],
      6,
      '19',
      '2026-07-01',
   ],
   ['ADI-667', 'Storybook a11y addon in CI', 'done', 2, 11, [9, 8], 6, '19', '2026-07-03'],

   /* ----------------------- Cycle 18 (completed) ------------------------- */
   [
      'ADI-641',
      'Fix Sheet drag-to-close threshold on touch',
      'done',
      2,
      13,
      [1],
      2,
      '18',
      '2026-06-08',
   ],
   ['ADI-642', 'Add Input OTP component', 'shipped', 2, 15, [2], 10, '18', '2026-06-10'],
   [
      'ADI-643',
      'Prevent layout shift when scrollbar appears with Dialog',
      'done',
      2,
      17,
      [1],
      2,
      '18',
      '2026-06-12',
   ],
   [
      'ADI-644',
      'Document controlled vs uncontrolled patterns',
      'done',
      3,
      19,
      [3],
      3,
      '18',
      '2026-06-14',
   ],
   [
      'ADI-645',
      'Spike: CSS anchor positioning for popovers',
      'canceled',
      4,
      0,
      [4],
      7,
      '18',
      '2026-06-16',
   ],
   [
      'ADI-646',
      'Refactor Avatar to support fallback delays',
      'done',
      4,
      2,
      [4],
      6,
      '18',
      '2026-06-18',
   ],

   /* ----------------------- Cycle 17 (completed) ------------------------- */
   [
      'ADI-621',
      'Dark mode: fix border contrast on nested cards',
      'done',
      3,
      4,
      [1, 6],
      1,
      '17',
      '2026-05-25',
   ],
   ['ADI-622', 'Ship Pagination compound component', 'shipped', 2, 6, [2], 9, '17', '2026-05-27'],
   [
      'ADI-623',
      'Add usage analytics to docs code copy events',
      'done',
      4,
      8,
      [3],
      3,
      '17',
      '2026-05-29',
   ],
   ['ADI-624', 'Textarea: autosize with max rows', 'done', 3, 10, [2], 10, '17', '2026-06-01'],
   [
      'ADI-625',
      'Fix Menubar closing when moving across triggers',
      'done',
      2,
      12,
      [1],
      8,
      '17',
      '2026-06-03',
   ],
   [
      'ADI-626',
      'Explore Houdini paint worklet for gradients',
      'canceled',
      4,
      14,
      [4],
      1,
      '17',
      '2026-06-05',
   ],

   /* ----------------------- Cycle 16 (completed) ------------------------- */
   [
      'ADI-601',
      'Set up visual regression tests with Playwright',
      'done',
      2,
      16,
      [9],
      6,
      '16',
      '2026-05-11',
   ],
   [
      'ADI-602',
      'Fix Tooltip flicker when trigger re-renders',
      'done',
      2,
      18,
      [1],
      7,
      '16',
      '2026-05-13',
   ],
   [
      'ADI-603',
      'Ship Scroll Area with custom scrollbar styling',
      'shipped',
      3,
      1,
      [2],
      0,
      '16',
      '2026-05-15',
   ],
   ['ADI-604', 'Normalize z-index scale across overlays', 'done', 2, 3, [4], 2, '16', '2026-05-17'],
   [
      'ADI-605',
      'Add French and Spanish docs translations',
      'done',
      4,
      5,
      [10],
      3,
      '16',
      '2026-05-19',
   ],

   /* --------------------------- Backlog stock ---------------------------- */
   [
      'ADI-801',
      'Explore container queries for responsive Card',
      'backlog',
      3,
      null,
      [0],
      6,
      '',
      '2026-06-02',
   ],
   [
      'ADI-802',
      'Tree view component with async children',
      'backlog',
      3,
      null,
      [2],
      6,
      '',
      '2026-06-05',
   ],
   [
      'ADI-803',
      'Color picker: eyedropper API integration',
      'backlog',
      4,
      null,
      [2],
      10,
      '',
      '2026-06-09',
   ],
   [
      'ADI-804',
      'Rich text editor primitives exploration',
      'backlog',
      3,
      null,
      [2, 4],
      null,
      '',
      '2026-06-12',
   ],
   [
      'ADI-805',
      'Drag handle affordance for sortable lists',
      'backlog',
      4,
      null,
      [0],
      9,
      '',
      '2026-06-15',
   ],
   ['ADI-806', 'Print stylesheet for docs pages', 'backlog', 4, null, [3], 3, '', '2026-06-18'],
   ['ADI-807', 'High-contrast theme preset', 'backlog', 3, null, [8, 6], 1, '', '2026-06-21'],
   [
      'ADI-808',
      'Skeleton auto-generation from component slots',
      'backlog',
      4,
      null,
      [4],
      6,
      '',
      '2026-06-24',
   ],
   ['ADI-809', 'Masonry layout primitive', 'backlog', 4, null, [2], 4, '', '2026-06-27'],
   [
      '