-- R3A: secure organization invitation storage and lifecycle functions.
-- Invitation tokens are generated by the application and only SHA-256 hashes are persisted.

begin;

create table public.organization_invitations (
   id uuid primary key default extensions.gen_random_uuid(),
   organization_id uuid not null references public.organizations (id) on delete cascade,
   email text not null check (char_length(email) between 3 and 254 and email = lower(email)),
   role public.organization_role not null default 'member' check (role <> 'owner'),
   token_hash text not null unique check (token_hash ~ '^[0-9a-f]{64}$'),
   invited_by uuid not null,
   created_at timestamptz not null default now(),
   expires_at timestamptz not null,
   accepted_at timestamptz,
   revoked_at timestamptz,
   unique (id, organization_id),
   foreign key (invited_by, organization_id)
      references public.organization_members (user_id, organization_id) on delete restrict,
   check (expires_at > created_at),
   check (not (accepted_at is not null and revoked_at is not null))
);

create table public.organization_invitation_teams (
   invitation_id uuid not null,
   organization_id uuid not null,
   team_id uuid not null,
   created_at timestamptz not null default now(),
   primary key (invitation_id, team_id),
   foreign key (invitation_id, organization_id)
      references public.organization_invitations (id, organization_id) on delete cascade,
   foreign key (team_id, organization_id)
      references public.teams (id, organization_id) on delete cascade
);

create index organization_invitations_org_email_idx
   on public.organization_invitations (organization_id, email, created_at desc);
create index organization_invitations_org_status_idx
   on public.organization_invitations (organization_id, accepted_at, revoked_at, expires_at);
create index organization_invitations_invited_by_idx
   on public.organization_invitations (invited_by, organization_id);
create index organization_invitation_teams_org_team_idx
   on public.organization_invitation_teams (organization_id, team_id);

alter table public.organization_invitations enable row level security;
alter table public.organization_invitation_teams enable row level security;

create policy organization_invitations_select_admins on public.organization_invitations
for select to authenticated
using (private.is_org_admin(organization_id));

create policy organization_invitation_teams_select_admins on public.organization_invitation_teams
for select to authenticated
using (private.is_org_admin(organization_id));

revoke all on table public.organization_invitations from anon, authenticated;
revoke all on table public.organization_invitation_teams from anon, authenticated;

grant select (
   id,
   organization_id,
   email,
   role,
   invited_by,
   created_at,
   expires_at,
   accepted_at,
   revoked_at
) on table public.organization_invitations to authenticated;
grant select on table public.organization_invitation_teams to authenticated;

create or replace function public.create_organization_invitation(
   p_organization_id uuid,
   p_email text,
   p_role public.organization_role,
   p_token_hash text,
   p_expires_at timestamptz,
   p_team_ids uuid[] default '{}'::uuid[]
)
returns table (
   invitation_id uuid,
   organization_id uuid,
   email text,
   role public.organization_role,
   invited_by uuid,
   created_at timestamptz,
   expires_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
   actor_id uuid := auth.uid();
   actor_role public.organization_role;
   normalized_email text := lower(trim(p_email));
   selected_team_ids uuid[];
   invitation_row public.organization_invitations%rowtype;
begin
   if actor_id is null then
      raise exception 'UNAUTHORIZED';
   end if;

   select member.role
     into actor_role
     from public.organization_members member
    where member.organization_id = p_organization_id
      and member.user_id = actor_id;

   if actor_role is null or actor_role not in ('owner', 'admin') then
      raise exception 'FORBIDDEN';
   end if;
   if p_role = 'owner' then
      raise exception 'INVALID_ROLE';
   end if;
   if actor_role = 'admin' and p_role = 'admin' then
      raise exception 'ADMIN_CANNOT_INVITE_ADMIN';
   end if;

   if char_length(normalized_email) < 3
      or char_length(normalized_email) > 254
      or position('@' in normalized_email) <= 1
      or position('@' in normalized_email) >= char_length(normalized_email) then
      raise exception 'INVALID_EMAIL';
   end if;
   if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
      raise exception 'INVALID_TOKEN_HASH';
   end if;
   if p_expires_at <= now() + interval '5 minutes'
      or p_expires_at > now() + interval '30 days' then
      raise exception 'INVALID_EXPIRY';
   end if;

   if exists (
      select 1
      from public.organization_members member
      join auth.users account on account.id = member.user_id
      where member.organization_id = p_organization_id
        and lower(account.email) = normalized_email
   ) then
      raise exception 'ALREADY_MEMBER';
   end if;

   if exists (
      select 1
      from public.organization_invitations existing
      where existing.organization_id = p_organization_id
        and existing.email = normalized_email
        and existing.accepted_at is null
        and existing.revoked_at is null
        and existing.expires_at > now()
   ) then
      raise exception 'INVITATION_ALREADY_PENDING';
   end if;

   select coalesce(array_agg(distinct requested.team_id order by requested.team_id), '{}'::uuid[])
     into selected_team_ids
     from unnest(coalesce(p_team_ids, '{}'::uuid[])) as requested(team_id)
    where requested.team_id is not null;

   if coalesce(array_length(selected_team_ids, 1), 0) > 50 then
      raise exception 'TOO_MANY_TEAMS';
   end if;

   if exists (
      select 1
      from unnest(selected_team_ids) as requested(team_id)
      left join public.teams team
        on team.id = requested.team_id
       and team.organization_id = p_organization_id
      where team.id is null
   ) then
      raise exception 'INVALID_TEAM';
   end if;

   insert into public.organization_invitations (
      organization_id,
      email,
      role,
      token_hash,
      invited_by,
      expires_at
   )
   values (
      p_organization_id,
      normalized_email,
      p_role,
      p_token_hash,
      actor_id,
      p_expires_at
   )
   returning * into invitation_row;

   insert into public.organization_invitation_teams (
      invitation_id,
      organization_id,
      team_id
   )
   select invitation_row.id, p_organization_id, requested.team_id
   from unnest(selected_team_ids) as requested(team_id);

   return query
   select
      invitation_row.id,
      invitation_row.organization_id,
      invitation_row.email,
      invitation_row.role,
      invitation_row.invited_by,
      invitation_row.created_at,
      invitation_row.expires_at;
end;
$$;

create or replace function public.revoke_organization_invitation(
   p_invitation_id uuid,
   p_organization_id uuid
)
returns table (
   invitation_id uuid,
   revoked_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
   actor_id uuid := auth.uid();
   actor_role public.organization_role;
   invitation_role public.organization_role;
   invitation_accepted_at timestamptz;
begin
   if actor_id is null then
      raise exception 'UNAUTHORIZED';
   end if;

   select member.role
     into actor_role
     from public.organization_members member
    where member.organization_id = p_organization_id
      and member.user_id = actor_id;

   if actor_role is null or actor_role not in ('owner', 'admin') then
      raise exception 'FORBIDDEN';
   end if;

   select invitation.role, invitation.accepted_at
     into invitation_role, invitation_accepted_at
     from public.organization_invitations invitation
    where invitation.id = p_invitation_id
      and invitation.organization_id = p_organization_id
    for update;

   if invitation_role is null then
      raise exception 'INVITATION_NOT_FOUND';
   end if;
   if actor_role = 'admin' and invitation_role = 'admin' then
      raise exception 'ADMIN_CANNOT_MANAGE_ADMIN_INVITE';
   end if;
   if invitation_accepted_at is not null then
      raise exception 'INVITATION_ALREADY_ACCEPTED';
   end if;

   update public.organization_invitations invitation
      set revoked_at = coalesce(invitation.revoked_at, now())
    where invitation.id = p_invitation_id
      and invitation.organization_id = p_organization_id;

   return query
   select invitation.id, invitation.revoked_at
   from public.organization_invitations invitation
   where invitation.id = p_invitation_id
     and invitation.organization_id = p_organization_id;
end;
$$;

create or replace function public.accept_organization_invitation(
   p_token_hash text
)
returns table (
   organization_id uuid,
   organization_slug text,
   role public.organization_role,
   accepted_at timestamptz
)
language plpgsql
security definer
set search_path = ''
as $$
declare
   actor_id uuid := auth.uid();
   actor_email text;
   invitation_row public.organization_invitations%rowtype;
   accepted_timestamp timestamptz := now();
   target_slug text;
begin
   if actor_id is null then
      raise exception 'UNAUTHORIZED';
   end if;
   if p_token_hash is null or p_token_hash !~ '^[0-9a-f]{64}$' then
      raise exception 'INVITATION_INVALID';
   end if;

   select lower(account.email)
     into actor_email
     from auth.users account
    where account.id = actor_id;

   if actor_email is null then
      raise exception 'INVITATION_EMAIL_MISMATCH';
   end if;

   select invitation.*
     into invitation_row
     from public.organization_invitations invitation
    where invitation.token_hash = p_token_hash
      and invitation.accepted_at is null
      and invitation.revoked_at is null
      and invitation.expires_at > now()
    for update;

   if invitation_row.id is null then
      raise exception 'INVITATION_INVALID';
   end if;
   if invitation_row.email <> actor_email then
      raise exception 'INVITATION_EMAIL_MISMATCH';
   end if;
   if invitation_row.role = 'owner' then
      raise exception 'INVALID_ROLE';
   end if;

   if exists (
      select 1
      from public.organization_members member
      where member.organization_id = invitation_row.organization_id
        and member.user_id = actor_id
   ) then
      raise exception 'ALREADY_MEMBER';
   end if;

   insert into public.organization_members (organization_id, user_id, role)
   values (invitation_row.organization_id, actor_id, invitation_row.role);

   insert into public.team_members (team_id, organization_id, user_id)
   select assignment.team_id, invitation_row.organization_id, actor_id
   from public.organization_invitation_teams assignment
   where assignment.invitation_id = invitation_row.id
     and assignment.organization_id = invitation_row.organization_id;

   update public.organization_invitations invitation
      set accepted_at = accepted_timestamp
    where invitation.id = invitation_row.id;

   select organization.slug
     into target_slug
     from public.organizations organization
    where organization.id = invitation_row.organization_id;

   return query
   select
      invitation_row.organization_id,
      target_slug,
      invitation_row.role,
      accepted_timestamp;
end;
$$;

revoke all on function public.create_organization_invitation(uuid, text, public.organization_role, text, timestamptz, uuid[]) from public;
revoke all on function public.revoke_organization_invitation(uuid, uuid) from public;
revoke all on function public.accept_organization_invitation(text) from public;

grant execute on function public.create_organization_invitation(uuid, text, public.organization_role, text, timestamptz, uuid[]) to authenticated;
grant execute on function public.revoke_organization_invitation(uuid, uuid) to authenticated;
grant execute on function public.accept_organization_invitation(text) to authenticated;

commit;
